language: node_js

node_js:
  - 12
  - 10

services:
  - docker

before_install:
  - docker pull postgres:latest
  - docker run -d --name database -e POSTGRES_PASSWORD=123456 -e POSTGRES_DB=car_rental_ms_test -p 5432:5432 postgres:latest

install:
  - yarn install

script:
  - yarn format
  - yarn lint
  - yarn test:unit --coverage
  - yarn test:e2e --runInBand
  - yarn build

after_script:
  - docker rm -f database
  - bash <(curl -s https://codecov.io/bash)
