version: "3"

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - database_test:/var/lib/postgresql/data

volumes:
  database_test:
